### ISSUE TITLE
yaposib 0.4.0 installation failing on Windows

### ISSUE THREAD

**Issue by devosgit** [coin-or/yaposib#5]
I am trying to get yaposib installed and working under Windows and use it as an interface to Symphony. 
pip install did not work, so I built yaposib from the version 0.4.0 files on github. I built boost.python 1.60.0 and Symphony 5.6.16.

When I run yaposib-config the following error occurs. 
**Traceback (most recent call last):
  File "c:/Python27/Scripts/yaposib-config", line 4, in <module>
    __import__('pkg_resources').run_script('yaposib==0.4.0', 'yaposib-config')
  File "C:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\yaposib-0.4.0-py2.7-win32.egg\EGG-INFO\scripts\yaposib-config", line 3, in <module>
    from coinor.yaposib.test.test_yaposib import main
  File "c:\Python27\lib\site-packages\yaposib-0.4.0-py2.7-win32.egg\coinor\yaposib\__init__.py", line 1, in <module>
    from _yaposib import *
ImportError: DLL load failed: The specified procedure could not be found.**

I have had no success diagnosing the cause of the error. I have rebuilt boost and yaposib several times trying different configurations.

@chmduquesne or @tkralphs , can you provide any insight into the cause of this error, and do you have a set of instructions that has been used for a successful build on Windows?

**Comment by chmduquesne** [comment]
This used to work on Windows, yes (I don't know whether it still does). I
don't do much linear programming these days, so I do not maintain this lib.
From your log, it looks like the yaposib DLL itself cannot be loaded. Is
there a yaposib.dll object somewhere in your build? In order to
investigate, the best approach would be to get python to load the file
directly as a DLL and see if that works. If it works, I would dig in the
direction of a misconfigured environment variable, otherwise it can be due
to a non backward-compatible change in the boost::python API.

**Comment by devosgit** [comment]
@tkralphs do you know if version 0.4.0 of yaposib on github can be built on Windows? Can you please share the process that you have used to build for Windows?
